name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        type: choice
        options:
          - dev
          - staging

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy dev
        if: inputs.environment == 'dev'
        run: echo "dev was deployed"

      - name: Deploy staging
        if: inputs.environment == 'staging'
        run: echo "staging was deployed"
